### ISSUE TITLE
Using fake-tweet with bootstrap CDN makes icons really small

### ISSUE THREAD

**Issue by Rainymood** [lluiscamino/fake-tweet#4]
Hi! I was using fake-tweet and then by importing the bootstrap CDN the icons became this

<img width="390" alt="Screenshot 2020-03-11 at 13 42 31" src="https://user-images.githubusercontent.com/2186137/76418060-4281b200-639e-11ea-9745-6ebc5e7ee819.png">

Any ideas on how to fix this?

**Comment by lluiscamino** [comment]
Hi,

I updated the component so the problem should be fixed with the new version 0.1.11 https://github.com/lluiscamino/fake-tweet/commit/3825cade5edaaeac5a859b9edf7720fc201f0429

Thanks for reporting the bug!

**Comment by Rainymood** [comment]
Aww yiss! Superb work! 

(Quick question, is it possible to use custom colours for the night version? They don't "match" the twitter UI colours in the web)

**Comment by lluiscamino** [comment]
There're 3 different views for the web version:
- Default (light)
- Dim (dark blue)
- Lights out (black)

The component only has the Default and "Lights out" modes, since they're the ones available on the mobile app. I'm currently working on including the "Dim" view, which I think is the one you want.

Anyway, if you go to the [Tweet.css](file) and search for `.nightmode`, you can easily edit the background color to the one you need (which I believe is `#15202b`).

**Comment by lluiscamino** [comment]
> Aww yiss! Superb work!
> 
> (Quick question, is it possible to use custom colours for the night version? They don't "match" the twitter UI colours in the web)

It is now possible with the latest update!  https://github.com/lluiscamino/fake-tweet/commit/643ef774488905e9c26f0fc41e3d705736b81df1
